services:
  web:
    build: .
    container_name: salesplan-web
    ports:
      - "8000:8000"
    environment:
      - TELEGRAM_TOKEN=8483686219:AAHbhh6ffOuz6yJ8FpUEeYOxrTwbo5hlDnY
      - ADMIN_CHAT_ID=12018296
      - DEEPSEEK_API_KEY=sk-dd8b8fec6a52478ebcb2c22d38d93af3
      - YOOKASSA_SHOP_ID=1325473
      - YOOKASSA_SECRET_KEY=live_A3Cax7aS-F_AC0IYEQPNQPk7xPeAUz8lKrk3kVGbLC4
      - ADMIN_USERNAME=admin
      - ADMIN_PASSWORD=SalesPlan$490!
    restart: unless-stopped
