version: '3.8'

services:
  web:
    build: .
    ports:
      - "8000:8000"
    environment:
      - TELEGRAM_TOKEN=8483686219:AAHbhh6ffOuz6yJ8FpUEeYOxrTwbo5hlDnY
      - ADMIN_CHAT_ID=433191114
      - DEEPSEEK_API_KEY=sk-dd8b8fec6a52478ebcb2c22d38d93af3
      - YKASSA_SHOP_ID=1325473
      - YKASSA_SECRET_KEY=live_A3Cax7aS-F_AC0IYEQPNQPk7xPeAUz8lKrk3kVGbLC4
      - ADMIN_USERNAME=admin
      - ADMIN_PASSWORD=SalesPlan$490!
    restart: always
